<?php


namespace Porto\Core\Resources;


use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class ResourceCollection extends AnonymousResourceCollection
{

    public function resolve($request = null) {
      return $this->collection->map(function ($val){
          $resourceIdentifier = new ResourceInclude($val);
          return $resourceIdentifier->transform();
      });
    }

    public function toArray($request) {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}